# Porta da aplicação
server.port=8080

# Banco de dados H2
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
springdoc.group-configs[0].group=1. DeliveryTech API
springdoc.group-configs[0].paths-to-match=/api/**
springdoc.group-configs[1].group=2. Monitoramento (Actuator)
springdoc.group-configs[1].paths-to-match=/actuator/**

# Segurança
spring.security.user.name=admin
spring.security.user.password=admin123

# Desenvolvimento
spring.devtools.restart.enabled=true

# Expor todos os endpoints do Actuator
management.endpoints.web.exposure.include=*
spring.application.name=deliverytech-api

# Mostrar detalhes do /actuator/health
management.endpoint.health.show-details=always

# Nível de log da aplicação
logging.level.root=INFO
logging.level.com.deliverytech=DEBUG
#spring.devtools.restart.enabled=false

# Adiciona um padr�o de log que inclui informa��es de tracing (Trace ID e Span ID)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Configura a probabilidade de amostragem de traces (1.0 = 100% dos traces ser�o enviados)
management.tracing.sampling.probability=1.0
